substitutions:
  name: "maidesite-desk"
  friendly_name: Maidesite Desk
  min_height: "620"
  max_height: "1263"

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  includes:
    - desk-control.h
  on_boot:
    priority: 800
    then:
      - uart.write: 
          [0xf1, 0xf1, 0x07, 0x00, 0x07, 0x7e, 0xf1, 0xf1, 0x08, 0x00, 0x08, 0x7e,
          0xf1, 0xf1, 0x09, 0x00, 0x09, 0x7e, 0xf1, 0xf1, 0x0c, 0x00, 0x0c, 0x7e,
          0xf1, 0xf1, 0x0e, 0x00, 0x0e, 0x7e]

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:
  level: DEBUG

api:
  encryption:
    key: !secret api_encryption_key

ota:
  platform: esphome
  password: !secret ota_password

improv_serial:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

uart:
  - id: maidesite_uart
    tx_pin: 26
    rx_pin: 27
    baud_rate: 9600
    debug:
      direction: BOTH
      dummy_receiver: false
      after:
        delimiter: "\n"
      sequence:
        - lambda: UARTDebug::log_string(direction, bytes);

globals:
  - id: desk_switch_state
    type: bool
    restore_value: no
    initial_value: "false"
  - id: last_height
    type: float
    initial_value: "0.0"
  - id: height_timer
    type: int
    initial_value: "0"
  - id: sitting_threshold
    type: float
    initial_value: "100.0"
  - id: standing_threshold
    type: float
    initial_value: "1200.0"

custom_component:
  - lambda: |-
      return {new DeskControl(id(maidesite_uart))};

sensor:
  - platform: template
    name: "Time at Current Height"
    id: time_at_current_height
    unit_of_measurement: "s"
    icon: "mdi:timer"
    accuracy_decimals: 0
    update_interval: 0.5s
    lambda: |-
      return id(height_timer);
  - platform: template
    name: "Current Height"
    id: desk_height
    unit_of_measurement: "cm"
    accuracy_decimals: 1
    icon: "mdi:arrow-up-down"
    update_interval: 0.5s
    lambda: |-
      return id(height_slider).state / 10.0;
  - platform: template
    name: "Sitting Position"
    id: "sensor_m1"
    icon: "mdi:seat-recline-normal"
    filters:
      - lambda: !lambda |-
          if (x < 1) {
            return {};
          }
          return x / 10;
  - platform: template
    name: "Standing Position"
    id: "sensor_m2"
    icon: "mdi:human-male"
    filters:
      - lambda: !lambda |-
          if (x < 1) {
            return {};
          }
          return x / 10;
  - platform: template
    name: "Custom Position 1"
    id: "sensor_m3"
    icon: "mdi:human-male-height-variant"
    filters:
      - lambda: !lambda |-
          if (x < 1) {
            return {};
          }
          return x / 10;
  - platform: template
    name: "Custom Position 2"
    id: "sensor_m4"
    icon: "mdi:human-male-height-variant"
    filters:
      - lambda: !lambda |-
          if (x < 1) {
            return {};
          }
          return x / 10;

text_sensor:
  - platform: template
    name: "Height Status"
    id: height_status
    icon: "mdi:human-male-female"
    update_interval: 10s
    lambda: |-
      float current_height = id(height_slider).state / 10.0;
      if (current_height >= 70.0 && current_height <= 80.0) {
        return std::string("Sitting");
      } else if (current_height >= 115.0 && current_height <= 125.0) {
        return std::string("Standing");
      } else {
        return std::string("Other");
      }

switch:
  - platform: template
    name: "Desk Lock"
    id: lock_mode
    lambda: return id(desk_switch_state);
    turn_on_action:
      - logger.log: "🟢 Desk is now unlocked and operational."
      - globals.set:
          id: desk_switch_state
          value: "true"
    turn_off_action:
      - logger.log: "🔴 Desk is now locked and non-operational."
      - globals.set:
          id: desk_switch_state
          value: "false"

button:
  - platform: template
    name: Up
    id: button_up
    icon: "mdi:arrow-up-bold"
    on_press:
      if:
        condition:
          switch.is_on: lock_mode
        then:
          - logger.log: "⚡ UP desk"
          - uart.write: [0xf1, 0xf1, 0x01, 0x00, 0x01, 0x7e]
  - platform: template
    name: Down
    id: button_down
    icon: "mdi:arrow-down-bold"
    on_press:
      if:
        condition:
          switch.is_on: lock_mode
        then:
          - logger.log: "⚡ DOWN desk"
          - uart.write: [0xf1, 0xf1, 0x02, 0x00, 0x02, 0x7e]
  - platform: template
    name: Sitting position
    id: button_sit
    icon: "mdi:seat-recline-normal"
    on_press:
      if:
        condition:
          switch.is_on: lock_mode
        then:
          - logger.log: "⚡ Sitting position"
          - uart.write: [0xf1, 0xf1, 0x05, 0x00, 0x05, 0x7e]
  - platform: template
    name: Stand position
    id: button_stand
    icon: "mdi:human-male"
    on_press:
      if:
        condition:
          switch.is_on: lock_mode
        then:
          - logger.log: "⚡ Stand position"
          - uart.write: [0xf1, 0xf1, 0x06, 0x00, 0x06, 0x7e]
  - platform: template
    name: Vibrate
    id: button_vibrate
    disabled_by_default: True
    icon: mdi:test-tube
    on_press:
      if:
        condition:
          switch.is_on: lock_mode
        then:
          - logger.log: "⚡ Vibrate desk button pressed!"
          - uart.write: [0xf1, 0xf1, 0x10, 0x00, 0x10, 0x7e]
  - platform: template
    name: Test
    id: button_test
    disabled_by_default: True
    icon: "mdi:test-tube"
    on_press:
      then:
        - logger.log: "🧪 Test desk"
        - uart.write: 
            [0xf1, 0xf1, 0x07, 0x00, 0x07, 0x7e, 0xf1, 0xf1, 0x08, 0x00, 0x08, 0x7e,
            0xf1, 0xf1, 0x09, 0x00, 0x09, 0x7e, 0xf1, 0xf1, 0x0c, 0x00, 0x0c, 0x7e,
            0xf1, 0xf1, 0x0e, 0x00, 0x0e, 0x7e]

number:
  - platform: template
    name: "Desk Height Control"
    id: height_slider
    step: 1
    min_value: ${min_height}
    max_value: ${max_height}
    mode: BOX
    set_action:
      if:
        condition:
          switch.is_on: lock_mode
        then:
          - uart.write: !lambda |-
              int a = (int(x) & 0xff);
              int b = ((int(x) >> 8) & 0xff);
              int c = (a + b + 0x80 + 0x02) & 0xff;
              return {0xf1, 0xf1, 0x80, 2, b, a, c, 0x7e, 0xf1, 0xf1, 0x1b, 0x00, 0x1b, 0x7e};

interval:
  - interval: 1s
    then:
      - lambda: |-
          float current_height = id(height_slider).state;
          if (current_height == id(last_height)) {
            id(height_timer)++;
          } else {
            id(height_timer) = 0;
            id(last_height) = current_height;
          }